M48
; DRILL file {KiCad 9.0.6} date 2026-04-10T14:22:55+0900
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2026-04-10T14:22:55+09:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.6
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1063
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.1260
%
G90
G05
T1
X4.0354Y-2.5591
X4.0354Y-5.5512
X7.7756Y-2.5591
X7.7756Y-5.5512
T2
X7.6Y-4.3
M30
